# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop

minecraft_version=26.1
loader_version=0.19.2
loom_version=1.16-SNAPSHOT
yarn_mappings=1.19+build.4

mod_version=2.0.0
maven_group=piglin.free.portals
archives_base_name=piglin-free-portals